#!/bin/bash
cd $(dirname $0)
for f in $(find . -type f | egrep -v \.git\|README\|infect\|defect); do
   f=${f:2}
   [ -f ~/$f ] && cp ~/$f $f
done
cp ~/.gitignore .explosion-pills-gitignore
cp ~/.gitconfig .explosion-pills-gitconfig
