#!/bin/bash
cd $(dirname $0)
replace=
for f in $(find . | egrep -v \.git\|README\|infect\|defect); do
   f=${f:2}
   if [ -n $f ]; then
      if [ -d $f ]; then
         if [ ! -d ~/$f ];then
            echo "directory $f does not exist.  Create now? (y)es, (n)o"
            read -s -n1 ch
            case $ch in
               y) mkdir ~/$f;;
               n) ;;
               *) echo "You must select (y) or (n)"; exit 1;;
            esac
         fi
      else
         if [ $(which $(basename $f) 2>/dev/null) ]; then
            echo "$f exists elsewhere in the path."
         fi
         if [ -f ~/$f ]; then
            if [ ! $replace ]; then
               decide=
               while [ ! $decide ]; do
                  echo "$f already exists at the destination. Replace? (y)es, (n)o, replace (a)ll, view (d)iff"
                  read -s -n1 ch
                  case $ch in
                     a) replace=true; cp $f ~/$f; decide=true;;
                     y) cp $f ~/$f; decide=true;;
                     n) decide=true;;
                     d)
                        [ $(which colordiff) ] && command=colordiff || command=diff
                        $command -U0 -wbB ~/$f $f | less -R
                     ;;
                     *) echo "You must select (y), (n), or (a)"; exit 1;;
                  esac
               done
            else
               cp $f ~/$f
            fi
         else
            cp $f ~/$f
         fi
      fi
   fi
done
